/**
 * Pool di analogie verbali per "L'Analogo".
 *
 * Struttura: A : B = C : ?
 *
 * Distrattori "facili" sono di altri campi semantici; quelli "duri" sono
 * semanticamente vicini alla risposta corretta (stesso campo categoriale).
 *
 * Ogni pool deve contenere almeno trialsPerSession_max items per garantire
 * unicità delle analogie all'interno di una sessione (vedi levels.ts).
 * Pool dimensionato a ~25 item per tipo per avere variabilità tra sessioni.
 */

import type { TipoAnalogia } from "./levels";

export interface AnalogiaItem {
  id:                string;
  tipo:              TipoAnalogia;
  a:                 string;
  b:                 string;
  c:                 string;
  risposta:          string;
  distrattoriFacili: readonly string[];
  distrattoriDuri:   readonly string[];
}

// ── OPPOSITIVE ──────────────────────────────────────────────────────────────
export const POOL_OPPOSITIVE: readonly AnalogiaItem[] = [
  { id: "opp01", tipo: "oppositiva",
    a: "CALDO",   b: "FREDDO",  c: "GIORNO", risposta: "NOTTE",
    distrattoriFacili: ["ALBERO", "ACQUA", "PANE"],
    distrattoriDuri:   ["SERA", "MATTINA", "TRAMONTO"] },
  { id: "opp02", tipo: "oppositiva",
    a: "GRANDE",  b: "PICCOLO", c: "ALTO",   risposta: "BASSO",
    distrattoriFacili: ["DOLCE", "FIORE", "SOLE"],
    distrattoriDuri:   ["LARGO", "STRETTO", "MEDIO"] },
  { id: "opp03", tipo: "oppositiva",
    a: "PIENO",   b: "VUOTO",   c: "APERTO", risposta: "CHIUSO",
    distrattoriFacili: ["MARE", "LIBRO", "FUOCO"],
    distrattoriDuri:   ["SOCCHIUSO", "SBARRATO", "SIGILLATO"] },
  { id: "opp04", tipo: "oppositiva",
    a: "VELOCE",  b: "LENTO",   c: "FORTE",  risposta: "DEBOLE",
    distrattoriFacili: ["VERDE", "PIOGGIA", "STELLA"],
    distrattoriDuri:   ["ROBUSTO", "GRACILE", "VIGOROSO"] },
  { id: "opp05", tipo: "oppositiva",
    a: "CHIARO",  b: "SCURO",   c: "DOLCE",  risposta: "AMARO",
    distrattoriFacili: ["PIATTO", "RUOTA", "NUVOLA"],
    distrattoriDuri:   ["SALATO", "ACIDO", "PICCANTE"] },
  { id: "opp06", tipo: "oppositiva",
    a: "GIOVANE", b: "ANZIANO", c: "RICCO",  risposta: "POVERO",
    distrattoriFacili: ["LUNA", "PESCE", "STRADA"],
    distrattoriDuri:   ["BENESTANTE", "AGIATO", "MODESTO"] },
  { id: "opp07", tipo: "oppositiva",
    a: "FELICE",  b: "TRISTE",  c: "CALMO",  risposta: "AGITATO",
    distrattoriFacili: ["GIALLO", "MONTE", "POSTA"],
    distrattoriDuri:   ["NERVOSO", "TRANQUILLO", "SERENO"] },
  { id: "opp08", tipo: "oppositiva",
    a: "DURO",    b: "MORBIDO", c: "RUVIDO", risposta: "LISCIO",
    distrattoriFacili: ["OROLOGIO", "MELA", "FINESTRA"],
    distrattoriDuri:   ["RAGGRINZITO", "GRANULOSO", "VELLUTATO"] },
  { id: "opp09", tipo: "oppositiva",
    a: "INIZIO",  b: "FINE",    c: "PRIMA",  risposta: "DOPO",
    distrattoriFacili: ["FIORE", "VIOLINO", "POLLO"],
    distrattoriDuri:   ["ADESSO", "DURANTE", "MENTRE"] },
  { id: "opp10", tipo: "oppositiva",
    a: "SOPRA",   b: "SOTTO",   c: "DENTRO", risposta: "FUORI",
    distrattoriFacili: ["BIANCO", "LIBRO", "GATTO"],
    distrattoriDuri:   ["ACCANTO", "VICINO", "LONTANO"] },
  { id: "opp11", tipo: "oppositiva",
    a: "GIORNO",  b: "NOTTE",   c: "ESTATE", risposta: "INVERNO",
    distrattoriFacili: ["MARTELLO", "FORCHETTA", "SCARPA"],
    distrattoriDuri:   ["AUTUNNO", "PRIMAVERA", "STAGIONE"] },
  { id: "opp12", tipo: "oppositiva",
    a: "ACCESO",  b: "SPENTO",  c: "ATTIVO", risposta: "FERMO",
    distrattoriFacili: ["CARTA", "TAZZA", "FILO"],
    distrattoriDuri:   ["IMMOBILE", "PIGRO", "RALLENTATO"] },
  { id: "opp13", tipo: "oppositiva",
    a: "PESANTE", b: "LEGGERO", c: "DENSO",  risposta: "RAREFATTO",
    distrattoriFacili: ["RUOTA", "TENDA", "MONETA"],
    distrattoriDuri:   ["COMPATTO", "GREVE", "PIENO"] },
  { id: "opp14", tipo: "oppositiva",
    a: "BIANCO",  b: "NERO",    c: "LUCE",   risposta: "BUIO",
    distrattoriFacili: ["LIBRO", "BARCA", "CAVALLO"],
    distrattoriDuri:   ["OMBRA", "TENEBRA", "PENOMBRA"] },
  { id: "opp15", tipo: "oppositiva",
    a: "BAGNATO", b: "ASCIUTTO", c: "UMIDO", risposta: "SECCO",
    distrattoriFacili: ["FORNO", "BOTTE", "ALA"],
    distrattoriDuri:   ["INZUPPATO", "FRADICIO", "ARIDO"] },
  { id: "opp16", tipo: "oppositiva",
    a: "RUMORE",  b: "SILENZIO", c: "CHIASSO", risposta: "QUIETE",
    distrattoriFacili: ["MOTORE", "TELA", "POLVERE"],
    distrattoriDuri:   ["SUSSURRO", "BISBIGLIO", "FRUSCIO"] },
  { id: "opp17", tipo: "oppositiva",
    a: "MAGRO",   b: "GRASSO",  c: "ESILE",  risposta: "ROBUSTO",
    distrattoriFacili: ["FUOCO", "PORTA", "FIUME"],
    distrattoriDuri:   ["FORMOSO", "TARCHIATO", "PRESTANTE"] },
  { id: "opp18", tipo: "oppositiva",
    a: "VITTORIA", b: "SCONFITTA", c: "TRIONFO", risposta: "DISFATTA",
    distrattoriFacili: ["TENDA", "ZUCCA", "RADIO"],
    distrattoriDuri:   ["FALLIMENTO", "INSUCCESSO", "ROVINA"] },
  { id: "opp19", tipo: "oppositiva",
    a: "GIUSTO",  b: "SBAGLIATO", c: "CORRETTO", risposta: "ERRATO",
    distrattoriFacili: ["MELA", "FINESTRA", "TROMBA"],
    distrattoriDuri:   ["INESATTO", "FALSO", "IMPRECISO"] },
  { id: "opp20", tipo: "oppositiva",
    a: "PARTENZA", b: "ARRIVO", c: "ANDATA", risposta: "RITORNO",
    distrattoriFacili: ["FORCHETTA", "PIANO", "MAGLIA"],
    distrattoriDuri:   ["VIAGGIO", "TRANSITO", "TAPPA"] },
  { id: "opp21", tipo: "oppositiva",
    a: "COSTRUIRE", b: "DISTRUGGERE", c: "EDIFICARE", risposta: "DEMOLIRE",
    distrattoriFacili: ["CANTARE", "DORMIRE", "LEGGERE"],
    distrattoriDuri:   ["SMANTELLARE", "ABBATTERE", "DIROCCARE"] },
  { id: "opp22", tipo: "oppositiva",
    a: "AMICO",   b: "NEMICO",  c: "ALLEATO", risposta: "AVVERSARIO",
    distrattoriFacili: ["VASO", "FIUME", "RUOTA"],
    distrattoriDuri:   ["RIVALE", "OPPOSITORE", "CONTENDENTE"] },
  { id: "opp23", tipo: "oppositiva",
    a: "ENTRATA", b: "USCITA",  c: "INGRESSO", risposta: "USCITA",
    distrattoriFacili: ["CIELO", "MOTORE", "QUADRO"],
    distrattoriDuri:   ["VARCO", "CORRIDOIO", "PORTONE"] },
  { id: "opp24", tipo: "oppositiva",
    a: "DIRITTO", b: "STORTO",  c: "RETTO",   risposta: "CURVO",
    distrattoriFacili: ["PIATTO", "TENDA", "ZAINO"],
    distrattoriDuri:   ["INCLINATO", "OBLIQUO", "PIEGATO"] },
  { id: "opp25", tipo: "oppositiva",
    a: "PULITO",  b: "SPORCO",  c: "LIMPIDO", risposta: "TORBIDO",
    distrattoriFacili: ["TRAMONTO", "MARTELLO", "VIOLINO"],
    distrattoriDuri:   ["FANGOSO", "OPACO", "ANNEBBIATO"] },
  { id: "opp26", tipo: "oppositiva",
    a: "CRUDO",   b: "COTTO",   c: "GREZZO",  risposta: "LAVORATO",
    distrattoriFacili: ["FIUME", "VIOLA", "POLLO"],
    distrattoriDuri:   ["RAFFINATO", "FINITO", "LIMATO"] },
  { id: "opp27", tipo: "oppositiva",
    a: "NUOVO",   b: "USATO",   c: "FRESCO",  risposta: "STANTIO",
    distrattoriFacili: ["NUVOLA", "BARCA", "CASCATA"],
    distrattoriDuri:   ["AVARIATO", "SCADUTO", "ANDATO"] },
  { id: "opp28", tipo: "oppositiva",
    a: "ENTRARE", b: "USCIRE",  c: "SALIRE",  risposta: "SCENDERE",
    distrattoriFacili: ["LEGGERE", "CANTARE", "DORMIRE"],
    distrattoriDuri:   ["ARRAMPICARSI", "CADERE", "PRECIPITARE"] },
  { id: "opp29", tipo: "oppositiva",
    a: "SVEGLIO", b: "ADDORMENTATO", c: "DESTO", risposta: "ASSOPITO",
    distrattoriFacili: ["MARTELLO", "ANGURIA", "CHITARRA"],
    distrattoriDuri:   ["DISTRATTO", "STORDITO", "INTONTITO"] },
  { id: "opp30", tipo: "oppositiva",
    a: "NOTO",    b: "IGNOTO",  c: "CONOSCIUTO", risposta: "SCONOSCIUTO",
    distrattoriFacili: ["FRUTTA", "PALAZZO", "RADIO"],
    distrattoriDuri:   ["ANONIMO", "MISTERIOSO", "OSCURO"] },
  { id: "opp31", tipo: "oppositiva",
    a: "POSSIBILE", b: "IMPOSSIBILE", c: "FATTIBILE", risposta: "IRREALIZZABILE",
    distrattoriFacili: ["FORCHETTA", "DIVANO", "TROMBA"],
    distrattoriDuri:   ["IMPRATICABILE", "UTOPICO", "INATTUABILE"] },
  { id: "opp32", tipo: "oppositiva",
    a: "RICORDARE", b: "DIMENTICARE", c: "MEMORIZZARE", risposta: "SCORDARE",
    distrattoriFacili: ["NUOTARE", "CUCINARE", "DIPINGERE"],
    distrattoriDuri:   ["IMPRIMERE", "OBLIARE", "TRASCURARE"] },
  { id: "opp33", tipo: "oppositiva",
    a: "CRESCERE", b: "DIMINUIRE", c: "AUMENTARE", risposta: "CALARE",
    distrattoriFacili: ["LEGGERE", "RIDERE", "DORMIRE"],
    distrattoriDuri:   ["SCEMARE", "RIDURSI", "DECRESCERE"] },
  { id: "opp34", tipo: "oppositiva",
    a: "AMARE",   b: "ODIARE",  c: "APPREZZARE", risposta: "DETESTARE",
    distrattoriFacili: ["CORRERE", "VOLARE", "GUIDARE"],
    distrattoriDuri:   ["ABORRIRE", "DISPREZZARE", "AVVERSARE"] },
  { id: "opp35", tipo: "oppositiva",
    a: "ACCETTARE", b: "RIFIUTARE", c: "APPROVARE", risposta: "RESPINGERE",
    distrattoriFacili: ["MELA", "FIUME", "VIOLINO"],
    distrattoriDuri:   ["BOCCIARE", "NEGARE", "OPPORSI"] },
  { id: "opp36", tipo: "oppositiva",
    a: "COMPRARE", b: "VENDERE", c: "ACQUISTARE", risposta: "CEDERE",
    distrattoriFacili: ["SALTARE", "PIANGERE", "RACCOGLIERE"],
    distrattoriDuri:   ["LIQUIDARE", "TRASFERIRE", "ALIENARE"] },
  { id: "opp37", tipo: "oppositiva",
    a: "NORMALE", b: "ECCEZIONALE", c: "COMUNE", risposta: "RARO",
    distrattoriFacili: ["LIBRO", "PALCO", "CIPOLLA"],
    distrattoriDuri:   ["INSOLITO", "UNICO", "PREZIOSO"] },
  { id: "opp38", tipo: "oppositiva",
    a: "UGUALE",  b: "DIVERSO", c: "IDENTICO", risposta: "DIFFERENTE",
    distrattoriFacili: ["MOTORE", "LATTE", "TENDA"],
    distrattoriDuri:   ["DISSIMILE", "DISTINTO", "VARIO"] },
  { id: "opp39", tipo: "oppositiva",
    a: "SEMPLICE", b: "COMPLESSO", c: "FACILE", risposta: "COMPLICATO",
    distrattoriFacili: ["TAVOLO", "PIANO", "CHIAVE"],
    distrattoriDuri:   ["ARTICOLATO", "INTRICATO", "ARDUO"] },
  { id: "opp40", tipo: "oppositiva",
    a: "INTERO",  b: "DIVISO",  c: "COMPLETO", risposta: "FRAMMENTATO",
    distrattoriFacili: ["MARE", "PRATO", "STELLA"],
    distrattoriDuri:   ["SPEZZATO", "SUDDIVISO", "PARZIALE"] },
  { id: "opp41", tipo: "oppositiva",
    a: "SPESSO",  b: "SOTTILE", c: "GROSSO",  risposta: "FINE",
    distrattoriFacili: ["FRUTTO", "POLENTA", "PORTA"],
    distrattoriDuri:   ["ESILE", "ESIGUO", "ASSOTTIGLIATO"] },
  { id: "opp42", tipo: "oppositiva",
    a: "SOLLEVARE", b: "ABBASSARE", c: "ALZARE", risposta: "POSARE",
    distrattoriFacili: ["CUCINARE", "STUDIARE", "BALLARE"],
    distrattoriDuri:   ["DEPORRE", "ADAGIARE", "APPOGGIARE"] },
  { id: "opp43", tipo: "oppositiva",
    a: "RIGIDO",  b: "FLESSIBILE", c: "TESO", risposta: "RILASSATO",
    distrattoriFacili: ["FIUME", "CHIODO", "POMERIGGIO"],
    distrattoriDuri:   ["MOLLEGGIATO", "ELASTICO", "DUTTILE"] },
  { id: "opp44", tipo: "oppositiva",
    a: "PROBABILE", b: "IMPROBABILE", c: "SICURO", risposta: "INCERTO",
    distrattoriFacili: ["ZAINO", "GUFO", "CITTÀ"],
    distrattoriDuri:   ["DUBBIO", "TITUBANTE", "ALEATORIO"] },
  { id: "opp45", tipo: "oppositiva",
    a: "PARTIRE", b: "RESTARE", c: "ANDARE", risposta: "RIMANERE",
    distrattoriFacili: ["LEGGERE", "GIOCARE", "PESCARE"],
    distrattoriDuri:   ["FERMARSI", "TRATTENERSI", "SOSTARE"] },
  { id: "opp46", tipo: "oppositiva",
    a: "ABBONDANTE", b: "SCARSO", c: "COPIOSO", risposta: "ESIGUO",
    distrattoriFacili: ["PIATTO", "CHIESA", "BOSCO"],
    distrattoriDuri:   ["MISERO", "MINIMO", "RIDOTTO"] },
  { id: "opp47", tipo: "oppositiva",
    a: "PRESENTE", b: "ASSENTE", c: "INCLUSO", risposta: "ESCLUSO",
    distrattoriFacili: ["PESCE", "RUOTA", "RADIO"],
    distrattoriDuri:   ["OMESSO", "TRALASCIATO", "ELIMINATO"] },
  { id: "opp48", tipo: "oppositiva",
    a: "INTERESSE", b: "NOIA", c: "CURIOSITÀ", risposta: "INDIFFERENZA",
    distrattoriFacili: ["LATTE", "CARTELLO", "TUBO"],
    distrattoriDuri:   ["DISINTERESSE", "APATIA", "DISTACCO"] },
  { id: "opp49", tipo: "oppositiva",
    a: "ATTACCO", b: "DIFESA", c: "OFFENSIVA", risposta: "RESISTENZA",
    distrattoriFacili: ["TENDA", "CIPRESSO", "POSTA"],
    distrattoriDuri:   ["RIPARO", "PROTEZIONE", "SCUDO"] },
  { id: "opp50", tipo: "oppositiva",
    a: "SUPERIORE", b: "INFERIORE", c: "PRIMO", risposta: "ULTIMO",
    distrattoriFacili: ["BARCA", "FORCHETTA", "RADIO"],
    distrattoriDuri:   ["FINALE", "POSTUMO", "TERMINALE"] },
] as const;

// ── FUNZIONALI ──────────────────────────────────────────────────────────────
export const POOL_FUNZIONALI: readonly AnalogiaItem[] = [
  { id: "fun01", tipo: "funzionale",
    a: "PENNELLO", b: "PITTORE",     c: "BISTURI",  risposta: "CHIRURGO",
    distrattoriFacili: ["POSTINO", "MARINAIO", "FALEGNAME"],
    distrattoriDuri:   ["INFERMIERE", "FARMACISTA", "DENTISTA"] },
  { id: "fun02", tipo: "funzionale",
    a: "MARTELLO", b: "FALEGNAME",   c: "VIOLINO",  risposta: "MUSICISTA",
    distrattoriFacili: ["CONTADINO", "AUTISTA", "PESCATORE"],
    distrattoriDuri:   ["BALLERINO", "CANTANTE", "ATTORE"] },
  { id: "fun03", tipo: "funzionale",
    a: "PENNA",    b: "SCRIVERE",    c: "FORBICI",  risposta: "TAGLIARE",
    distrattoriFacili: ["DORMIRE", "CAMMINARE", "CANTARE"],
    distrattoriDuri:   ["INCOLLARE", "PIEGARE", "STRAPPARE"] },
  { id: "fun04", tipo: "funzionale",
    a: "OCCHI",    b: "VEDERE",      c: "ORECCHIE", risposta: "SENTIRE",
    distrattoriFacili: ["CORRERE", "NUOTARE", "MANGIARE"],
    distrattoriDuri:   ["TOCCARE", "PARLARE", "ANNUSARE"] },
  { id: "fun05", tipo: "funzionale",
    a: "FARINA",   b: "PANE",        c: "UVA",      risposta: "VINO",
    distrattoriFacili: ["BICICLETTA", "QUADRO", "TELEFONO"],
    distrattoriDuri:   ["MARMELLATA", "SUCCO", "ACETO"] },
  { id: "fun06", tipo: "funzionale",
    a: "CHIAVE",   b: "APRIRE",      c: "LUCCHETTO", risposta: "CHIUDERE",
    distrattoriFacili: ["VOLARE", "DIPINGERE", "CUCINARE"],
    distrattoriDuri:   ["SPINGERE", "TIRARE", "GIRARE"] },
  { id: "fun07", tipo: "funzionale",
    a: "AGO",      b: "SARTO",       c: "ZAPPA",    risposta: "CONTADINO",
    distrattoriFacili: ["POLIZIOTTO", "MEDICO", "CUOCO"],
    distrattoriDuri:   ["GIARDINIERE", "FIORAIO", "VENDEMMIATORE"] },
  { id: "fun08", tipo: "funzionale",
    a: "FORNO",    b: "CUOCERE",     c: "FRIGO",    risposta: "RAFFREDDARE",
    distrattoriFacili: ["CANTARE", "LEGGERE", "GUIDARE"],
    distrattoriDuri:   ["BOLLIRE", "CONGELARE", "SCONGELARE"] },
  { id: "fun09", tipo: "funzionale",
    a: "SCOPA",    b: "SPAZZARE",    c: "SPUGNA",   risposta: "LAVARE",
    distrattoriFacili: ["VOLARE", "CORRERE", "DIPINGERE"],
    distrattoriDuri:   ["ASCIUGARE", "STIRARE", "LUCIDARE"] },
  { id: "fun10", tipo: "funzionale",
    a: "GESSO",    b: "INSEGNANTE",  c: "FISCHIETTO", risposta: "ARBITRO",
    distrattoriFacili: ["ASTRONAUTA", "PILOTA", "FORNAIO"],
    distrattoriDuri:   ["ALLENATORE", "GIOCATORE", "GUARDALINEE"] },
  { id: "fun11", tipo: "funzionale",
    a: "MACCHINA", b: "AUTISTA",     c: "AEREO",    risposta: "PILOTA",
    distrattoriFacili: ["FIORAIO", "MURATORE", "TIPOGRAFO"],
    distrattoriDuri:   ["HOSTESS", "MECCANICO", "PASSEGGERO"] },
  { id: "fun12", tipo: "funzionale",
    a: "LATTE",    b: "FORMAGGIO",   c: "OLIVA",    risposta: "OLIO",
    distrattoriFacili: ["CAMICIA", "DIVANO", "RADIO"],
    distrattoriDuri:   ["BURRO", "SALSA", "ACETO"] },
  { id: "fun13", tipo: "funzionale",
    a: "BUSSOLA",  b: "ORIENTARE",   c: "TERMOMETRO", risposta: "MISURARE",
    distrattoriFacili: ["DANZARE", "DORMIRE", "GIOCARE"],
    distrattoriDuri:   ["CALCOLARE", "OSSERVARE", "REGISTRARE"] },
  { id: "fun14", tipo: "funzionale",
    a: "CAMERIERE", b: "RISTORANTE", c: "BARISTA", risposta: "BAR",
    distrattoriFacili: ["FORESTA", "STADIO", "MUSEO"],
    distrattoriDuri:   ["TRATTORIA", "PASTICCERIA", "ENOTECA"] },
  { id: "fun15", tipo: "funzionale",
    a: "BAULE",    b: "CONTENERE",   c: "PONTE",    risposta: "COLLEGARE",
    distrattoriFacili: ["RIDERE", "CANTARE", "NUOTARE"],
    distrattoriDuri:   ["SOSTENERE", "ATTRAVERSARE", "UNIRE"] },
  { id: "fun16", tipo: "funzionale",
    a: "CARTELLO", b: "SEGNALARE",   c: "SIRENA",   risposta: "AVVISARE",
    distrattoriFacili: ["GIOCARE", "PESCARE", "STIRARE"],
    distrattoriDuri:   ["RICHIAMARE", "ALLERTARE", "ANNUNCIARE"] },
  { id: "fun17", tipo: "funzionale",
    a: "PALA",     b: "SCAVARE",     c: "FALCE",    risposta: "MIETERE",
    distrattoriFacili: ["VOLARE", "DIPINGERE", "DORMIRE"],
    distrattoriDuri:   ["RACCOGLIERE", "POTARE", "ARARE"] },
  { id: "fun18", tipo: "funzionale",
    a: "PIANOFORTE", b: "PIANISTA",  c: "CHITARRA", risposta: "CHITARRISTA",
    distrattoriFacili: ["GIORNALISTA", "FOTOGRAFO", "ASTRONAUTA"],
    distrattoriDuri:   ["VIOLINISTA", "BATTERISTA", "FLAUTISTA"] },
  { id: "fun19", tipo: "funzionale",
    a: "OMBRELLO", b: "PIOGGIA",     c: "OCCHIALI", risposta: "SOLE",
    distrattoriFacili: ["CHITARRA", "RUOTA", "ARMADIO"],
    distrattoriDuri:   ["VENTO", "NEVE", "CALORE"] },
  { id: "fun20", tipo: "funzionale",
    a: "API",      b: "MIELE",       c: "MUCCA",    risposta: "LATTE",
    distrattoriFacili: ["RADIO", "QUADRO", "TENDA"],
    distrattoriDuri:   ["BURRO", "UOVO", "LANA"] },
  { id: "fun21", tipo: "funzionale",
    a: "MEDICO",   b: "CURARE",      c: "GIUDICE",  risposta: "GIUDICARE",
    distrattoriFacili: ["CANTARE", "GIOCARE", "VIAGGIARE"],
    distrattoriDuri:   ["DIFENDERE", "ACCUSARE", "TESTIMONIARE"] },
  { id: "fun22", tipo: "funzionale",
    a: "FUCILE",   b: "CACCIATORE",  c: "CANNA",    risposta: "PESCATORE",
    distrattoriFacili: ["ARCHITETTO", "POSTINO", "FORNAIO"],
    distrattoriDuri:   ["MARINAIO", "SUBACQUEO", "PESCIVENDOLO"] },
  { id: "fun23", tipo: "funzionale",
    a: "SPADA",    b: "GUERRIERO",   c: "LIBRO",    risposta: "STUDIOSO",
    distrattoriFacili: ["GIARDINIERE", "BALLERINA", "CUOCO"],
    distrattoriDuri:   ["LETTORE", "SCRITTORE", "BIBLIOTECARIO"] },
  { id: "fun24", tipo: "funzionale",
    a: "SAPONE",   b: "PULIRE",      c: "COLLA",    risposta: "INCOLLARE",
    distrattoriFacili: ["VOLARE", "CANTARE", "GUIDARE"],
    distrattoriDuri:   ["SIGILLARE", "FISSARE", "ATTACCARE"] },
  { id: "fun25", tipo: "funzionale",
    a: "CANDELA",  b: "ILLUMINARE",  c: "STUFA",    risposta: "RISCALDARE",
    distrattoriFacili: ["LEGGERE", "DORMIRE", "VOLARE"],
    distrattoriDuri:   ["BRUCIARE", "FONDERE", "ASCIUGARE"] },
  { id: "fun26", tipo: "funzionale",
    a: "POMPIERE", b: "INCENDIO",    c: "MEDICO",   risposta: "MALATTIA",
    distrattoriFacili: ["BICICLETTA", "QUADRO", "RADIO"],
    distrattoriDuri:   ["FERITA", "CURA", "PAZIENTE"] },
  { id: "fun27", tipo: "funzionale",
    a: "RUBINETTO", b: "ACQUA",      c: "INTERRUTTORE", risposta: "LUCE",
    distrattoriFacili: ["FORESTA", "RADICE", "CAVALLO"],
    distrattoriDuri:   ["CORRENTE", "LAMPADA", "PRESA"] },
  { id: "fun28", tipo: "funzionale",
    a: "SECCHIO",  b: "RACCOGLIERE", c: "ANNAFFIATOIO", risposta: "INNAFFIARE",
    distrattoriFacili: ["CANTARE", "DORMIRE", "GUIDARE"],
    distrattoriDuri:   ["BAGNARE", "IRRIGARE", "INUMIDIRE"] },
  { id: "fun29", tipo: "funzionale",
    a: "ALBERO",   b: "FRUTTO",      c: "GALLINA",  risposta: "UOVO",
    distrattoriFacili: ["BICICLETTA", "FINESTRA", "MARTELLO"],
    distrattoriDuri:   ["POLLO", "PIUMA", "PULCINO"] },
  { id: "fun30", tipo: "funzionale",
    a: "CACCIATORE", b: "PREDA",     c: "AGRICOLTORE", risposta: "RACCOLTO",
    distrattoriFacili: ["RADIO", "PIATTO", "ZAINO"],
    distrattoriDuri:   ["CAMPO", "ARATRO", "SEMINA"] },
  { id: "fun31", tipo: "funzionale",
    a: "SARTORIA", b: "SARTO",       c: "PANIFICIO", risposta: "PANETTIERE",
    distrattoriFacili: ["AVVOCATO", "PILOTA", "ARBITRO"],
    distrattoriDuri:   ["PASTICCERE", "FORNAIO", "PIZZAIOLO"] },
  { id: "fun32", tipo: "funzionale",
    a: "SCALPELLO", b: "SCULTORE",   c: "TASTIERA", risposta: "SCRITTORE",
    distrattoriFacili: ["CONTADINO", "MARINAIO", "POSTINO"],
    distrattoriDuri:   ["GIORNALISTA", "POETA", "ROMANZIERE"] },
  { id: "fun33", tipo: "funzionale",
    a: "PINZA",    b: "AFFERRARE",   c: "MARTELLO", risposta: "COLPIRE",
    distrattoriFacili: ["VOLARE", "DIPINGERE", "LEGGERE"],
    distrattoriDuri:   ["PICCHIARE", "BATTERE", "PERCUOTERE"] },
  { id: "fun34", tipo: "funzionale",
    a: "RASOIO",   b: "RADERE",      c: "SPAZZOLINO", risposta: "LAVARE",
    distrattoriFacili: ["NUOTARE", "GUIDARE", "CANTARE"],
    distrattoriDuri:   ["PULIRE", "SFREGARE", "STROFINARE"] },
  { id: "fun35", tipo: "funzionale",
    a: "BANCA",    b: "DENARO",      c: "BIBLIOTECA", risposta: "LIBRI",
    distrattoriFacili: ["VEICOLO", "PIANTA", "EMOZIONE"],
    distrattoriDuri:   ["RIVISTE", "GIORNALI", "DOCUMENTI"] },
  { id: "fun36", tipo: "funzionale",
    a: "GIORNALISTA", b: "NOTIZIA",  c: "STORICO",  risposta: "STORIA",
    distrattoriFacili: ["DOLCE", "PESCE", "AUTO"],
    distrattoriDuri:   ["CRONACA", "VICENDA", "MEMORIA"] },
  { id: "fun37", tipo: "funzionale",
    a: "VERNICE",  b: "DIPINGERE",   c: "INCHIOSTRO", risposta: "SCRIVERE",
    distrattoriFacili: ["DORMIRE", "CORRERE", "CANTARE"],
    distrattoriDuri:   ["VERGARE", "ANNOTARE", "STILARE"] },
  { id: "fun38", tipo: "funzionale",
    a: "NOTAIO",   b: "ATTI",        c: "AVVOCATO", risposta: "CAUSE",
    distrattoriFacili: ["CONTADINO", "FORNAIO", "PILOTA"],
    distrattoriDuri:   ["PROCESSI", "SENTENZE", "RICORSI"] },
  { id: "fun39", tipo: "funzionale",
    a: "TIMONE",   b: "NAVE",        c: "MANUBRIO", risposta: "BICICLETTA",
    distrattoriFacili: ["LAVATRICE", "FORNO", "DIVANO"],
    distrattoriDuri:   ["MOTO", "SCOOTER", "MONOPATTINO"] },
  { id: "fun40", tipo: "funzionale",
    a: "BAMBOLA",  b: "BAMBINA",     c: "TRENINO",  risposta: "BAMBINO",
    distrattoriFacili: ["MEDICO", "PILOTA", "CUOCO"],
    distrattoriDuri:   ["RAGAZZO", "GIOVANE", "FIGLIO"] },
  { id: "fun41", tipo: "funzionale",
    a: "STETOSCOPIO", b: "CUORE",    c: "MICROSCOPIO", risposta: "CELLULA",
    distrattoriFacili: ["MUSICA", "TENDA", "ZAINO"],
    distrattoriDuri:   ["BATTERIO", "VIRUS", "TESSUTO"] },
  { id: "fun42", tipo: "funzionale",
    a: "RADAR",    b: "INDIVIDUARE", c: "SISMOGRAFO", risposta: "REGISTRARE",
    distrattoriFacili: ["GIOCARE", "RIDERE", "DORMIRE"],
    distrattoriDuri:   ["RILEVARE", "MISURARE", "TRACCIARE"] },
  { id: "fun43", tipo: "funzionale",
    a: "POLLICE",  b: "MANO",        c: "ALLUCE",   risposta: "PIEDE",
    distrattoriFacili: ["NUVOLA", "GIARDINO", "POSTA"],
    distrattoriDuri:   ["TALLONE", "CAVIGLIA", "PIANTA"] },
  { id: "fun44", tipo: "funzionale",
    a: "RIBES",    b: "MARMELLATA",  c: "ARANCIA",  risposta: "SUCCO",
    distrattoriFacili: ["MARTELLO", "BARCA", "PORTA"],
    distrattoriDuri:   ["SCIROPPO", "SPREMUTA", "AGRUME"] },
  { id: "fun45", tipo: "funzionale",
    a: "CERA",     b: "CANDELA",     c: "COTONE",   risposta: "MAGLIA",
    distrattoriFacili: ["LIBRO", "RADIO", "PORTA"],
    distrattoriDuri:   ["TESSUTO", "FILO", "STOFFA"] },
  { id: "fun46", tipo: "funzionale",
    a: "CIPOLLA",  b: "LACRIMA",     c: "PEPERONCINO", risposta: "BRUCIORE",
    distrattoriFacili: ["BICICLETTA", "TENDA", "QUADRO"],
    distrattoriDuri:   ["PIZZICORE", "PRURITO", "FIAMMA"] },
  { id: "fun47", tipo: "funzionale",
    a: "NUVOLA",   b: "PIOGGIA",     c: "SOLE",     risposta: "LUCE",
    distrattoriFacili: ["FORCHETTA", "PIANO", "RADIO"],
    distrattoriDuri:   ["CALORE", "RAGGIO", "BAGLIORE"] },
  { id: "fun48", tipo: "funzionale",
    a: "PITTORE",  b: "TELA",        c: "SCULTORE", risposta: "MARMO",
    distrattoriFacili: ["FORNAIO", "PILOTA", "ASTRONAUTA"],
    distrattoriDuri:   ["CRETA", "ARGILLA", "GESSO"] },
  { id: "fun49", tipo: "funzionale",
    a: "CHEF",     b: "RICETTA",     c: "ARCHITETTO", risposta: "PROGETTO",
    distrattoriFacili: ["FIORE", "MARE", "TROMBA"],
    distrattoriDuri:   ["DISEGNO", "PIANTA", "BOZZA"] },
  { id: "fun50", tipo: "funzionale",
    a: "ACCIAIO",  b: "TEMPRARE",    c: "VINO",     risposta: "STAGIONARE",
    distrattoriFacili: ["CANTARE", "VOLARE", "DORMIRE"],
    distrattoriDuri:   ["INVECCHIARE", "AFFINARE", "MATURARE"] },
] as const;

// ── CATEGORIALI ─────────────────────────────────────────────────────────────
export const POOL_CATEGORIALI: readonly AnalogiaItem[] = [
  { id: "cat01", tipo: "categoriale",
    a: "MELA",     b: "FRUTTO",       c: "ROSA",      risposta: "FIORE",
    distrattoriFacili: ["STRUMENTO", "MOBILE", "ANIMALE"],
    distrattoriDuri:   ["FOGLIA", "PIANTA", "GIARDINO"] },
  { id: "cat02", tipo: "categoriale",
    a: "CANE",     b: "MAMMIFERO",    c: "PASSERO",   risposta: "UCCELLO",
    distrattoriFacili: ["VEICOLO", "CIBO", "STELLA"],
    distrattoriDuri:   ["PIUMA", "NIDO", "ALA"] },
  { id: "cat03", tipo: "categoriale",
    a: "VIOLINO",  b: "STRUMENTO",    c: "SEDIA",     risposta: "MOBILE",
    distrattoriFacili: ["FRUTTO", "PIANTA", "VEICOLO"],
    distrattoriDuri:   ["LEGNO", "CUSCINO", "POLTRONA"] },
  { id: "cat04", tipo: "categoriale",
    a: "ROSSO",    b: "COLORE",       c: "QUADRATO",  risposta: "FORMA",
    distrattoriFacili: ["NUMERO", "PROFESSIONE", "STAGIONE"],
    distrattoriDuri:   ["LATO", "DIMENSIONE", "BORDO"] },
  { id: "cat05", tipo: "categoriale",
    a: "AUTO",     b: "VEICOLO",      c: "TROTA",     risposta: "PESCE",
    distrattoriFacili: ["INSETTO", "FIORE", "BEVANDA"],
    distrattoriDuri:   ["MARE", "AMO", "SCAGLIA"] },
  { id: "cat06", tipo: "categoriale",
    a: "LUNEDÌ",   b: "GIORNO",       c: "GENNAIO",   risposta: "MESE",
    distrattoriFacili: ["MOBILE", "STRUMENTO", "FRUTTO"],
    distrattoriDuri:   ["SETTIMANA", "ANNO", "STAGIONE"] },
  { id: "cat07", tipo: "categoriale",
    a: "DOTTORE",  b: "PROFESSIONE",  c: "MARTELLO",  risposta: "ATTREZZO",
    distrattoriFacili: ["ANIMALE", "EMOZIONE", "PAESE"],
    distrattoriDuri:   ["CHIODO", "OFFICINA", "OPERAIO"] },
  { id: "cat08", tipo: "categoriale",
    a: "PAURA",    b: "EMOZIONE",     c: "DUE",       risposta: "NUMERO",
    distrattoriFacili: ["MESE", "FIORE", "PESCE"],
    distrattoriDuri:   ["CIFRA", "MATEMATICA", "CONTEGGIO"] },
  { id: "cat09", tipo: "categoriale",
    a: "TRIANGOLO", b: "FIGURA",      c: "ITALIANO",  risposta: "LINGUA",
    distrattoriFacili: ["PIANETA", "ALIMENTO", "TESSUTO"],
    distrattoriDuri:   ["DIALETTO", "PAROLA", "ALFABETO"] },
  { id: "cat10", tipo: "categoriale",
    a: "PINO",     b: "ALBERO",       c: "MARGHERITA", risposta: "FIORE",
    distrattoriFacili: ["MOBILE", "VEICOLO", "STRUMENTO"],
    distrattoriDuri:   ["PETALO", "STELO", "POLLINE"] },
  { id: "cat11", tipo: "categoriale",
    a: "PIOGGIA",  b: "METEO",        c: "FEBBRE",    risposta: "SINTOMO",
    distrattoriFacili: ["MOBILE", "CIBO", "VEICOLO"],
    distrattoriDuri:   ["MALATTIA", "CURA", "MEDICINA"] },
  { id: "cat12", tipo: "categoriale",
    a: "ROMA",     b: "CITTÀ",        c: "ITALIA",    risposta: "NAZIONE",
    distrattoriFacili: ["EMOZIONE", "COLORE", "FRUTTO"],
    distrattoriDuri:   ["REGIONE", "CONTINENTE", "PROVINCIA"] },
  { id: "cat13", tipo: "categoriale",
    a: "ORO",      b: "METALLO",      c: "RUBINO",    risposta: "PIETRA",
    distrattoriFacili: ["ANIMALE", "MESE", "BEVANDA"],
    distrattoriDuri:   ["DIAMANTE", "GIOIELLO", "MINIERA"] },
  { id: "cat14", tipo: "categoriale",
    a: "BALENA",   b: "MAMMIFERO",    c: "AQUILA",    risposta: "UCCELLO",
    distrattoriFacili: ["FRUTTO", "MINERALE", "VEICOLO"],
    distrattoriDuri:   ["RAPACE", "PREDATORE", "VOLATILE"] },
  { id: "cat15", tipo: "categoriale",
    a: "VINO",     b: "BEVANDA",      c: "PASTA",     risposta: "ALIMENTO",
    distrattoriFacili: ["ANIMALE", "MESE", "PROFESSIONE"],
    distrattoriDuri:   ["GRANO", "PIATTO", "CONDIMENTO"] },
  { id: "cat16", tipo: "categoriale",
    a: "POMERIGGIO", b: "PARTE DEL GIORNO", c: "LUGLIO", risposta: "MESE",
    distrattoriFacili: ["MOBILE", "STRUMENTO", "FRUTTO"],
    distrattoriDuri:   ["ESTATE", "VACANZA", "CALDO"] },
  { id: "cat17", tipo: "categoriale",
    a: "RAME",     b: "METALLO",      c: "QUERCIA",   risposta: "ALBERO",
    distrattoriFacili: ["EMOZIONE", "BEVANDA", "FORMA"],
    distrattoriDuri:   ["FAGGIO", "BOSCO", "LEGNO"] },
  { id: "cat18", tipo: "categoriale",
    a: "TENNIS",   b: "SPORT",        c: "SCACCHI",   risposta: "GIOCO",
    distrattoriFacili: ["FRUTTO", "VEICOLO", "FIORE"],
    distrattoriDuri:   ["DAMA", "BRIDGE", "PASSATEMPO"] },
  { id: "cat19", tipo: "categoriale",
    a: "MEDUSA",   b: "INVERTEBRATO", c: "AQUILA",    risposta: "VERTEBRATO",
    distrattoriFacili: ["MOBILE", "METALLO", "EMOZIONE"],
    distrattoriDuri:   ["VOLATILE", "RAPACE", "PREDATORE"] },
  { id: "cat20", tipo: "categoriale",
    a: "DOLLARO",  b: "VALUTA",       c: "GIAPPONESE", risposta: "LINGUA",
    distrattoriFacili: ["ANIMALE", "MOBILE", "FRUTTO"],
    distrattoriDuri:   ["NAZIONALITÀ", "POPOLO", "CULTURA"] },
  { id: "cat21", tipo: "categoriale",
    a: "VELLUTO",  b: "TESSUTO",      c: "MARMO",     risposta: "PIETRA",
    distrattoriFacili: ["ANIMALE", "FRUTTO", "BEVANDA"],
    distrattoriDuri:   ["GRANITO", "STATUA", "SCULTURA"] },
  { id: "cat22", tipo: "categoriale",
    a: "SAHARA",   b: "DESERTO",      c: "TIRRENO",   risposta: "MARE",
    distrattoriFacili: ["EMOZIONE", "FORMA", "PROFESSIONE"],
    distrattoriDuri:   ["LAGO", "FIUME", "OCEANO"] },
  { id: "cat23", tipo: "categoriale",
    a: "AMETISTA", b: "PIETRA",       c: "EBANO",     risposta: "LEGNO",
    distrattoriFacili: ["MESE", "VEICOLO", "FIORE"],
    distrattoriDuri:   ["MOGANO", "FORESTA", "TRONCO"] },
  { id: "cat24", tipo: "categoriale",
    a: "EURO",     b: "MONETA",       c: "METRO",     risposta: "MISURA",
    distrattoriFacili: ["EMOZIONE", "ANIMALE", "STAGIONE"],
    distrattoriDuri:   ["CHILO", "LITRO", "UNITÀ"] },
  { id: "cat25", tipo: "categoriale",
    a: "VENERE",   b: "PIANETA",      c: "SIRIO",     risposta: "STELLA",
    distrattoriFacili: ["FRUTTO", "VEICOLO", "MOBILE"],
    distrattoriDuri:   ["LUNA", "GALASSIA", "COMETA"] },
  { id: "cat26", tipo: "categoriale",
    a: "SQUALO",   b: "PESCE",        c: "LUPO",      risposta: "MAMMIFERO",
    distrattoriFacili: ["MOBILE", "STAGIONE", "EMOZIONE"],
    distrattoriDuri:   ["PREDATORE", "CARNIVORO", "CANIDE"] },
  { id: "cat27", tipo: "categoriale",
    a: "CASTAGNO", b: "ALBERO",       c: "TULIPANO",  risposta: "FIORE",
    distrattoriFacili: ["BEVANDA", "PROFESSIONE", "VEICOLO"],
    distrattoriDuri:   ["BULBO", "STELO", "GIARDINO"] },
  { id: "cat28", tipo: "categoriale",
    a: "APE",      b: "INSETTO",      c: "VIPERA",    risposta: "RETTILE",
    distrattoriFacili: ["FORMA", "BEVANDA", "STRUMENTO"],
    distrattoriDuri:   ["SERPE", "SCAGLIA", "VELENO"] },
  { id: "cat29", tipo: "categoriale",
    a: "TROTA",    b: "PESCE",        c: "COCCINELLA", risposta: "INSETTO",
    distrattoriFacili: ["EMOZIONE", "PROFESSIONE", "STAGIONE"],
    distrattoriDuri:   ["FARFALLA", "VOLATILE", "ALA"] },
  { id: "cat30", tipo: "categoriale",
    a: "PARIGI",   b: "CITTÀ",        c: "SENNA",     risposta: "FIUME",
    distrattoriFacili: ["FRUTTO", "ANIMALE", "MOBILE"],
    distrattoriDuri:   ["AFFLUENTE", "TORRENTE", "LAGO"] },
  { id: "cat31", tipo: "categoriale",
    a: "SPAGNOLO", b: "LINGUA",       c: "SPAGNA",    risposta: "NAZIONE",
    distrattoriFacili: ["VEICOLO", "EMOZIONE", "MOBILE"],
    distrattoriDuri:   ["STATO", "PATRIA", "REGNO"] },
  { id: "cat32", tipo: "categoriale",
    a: "PIZZA",    b: "PIATTO",       c: "ESPRESSO",  risposta: "BEVANDA",
    distrattoriFacili: ["ANIMALE", "MOBILE", "FRUTTO"],
    distrattoriDuri:   ["CAFFÈ", "BAR", "CIALDA"] },
  { id: "cat33", tipo: "categoriale",
    a: "PROSCIUTTO", b: "SALUME",     c: "PARMIGIANO", risposta: "FORMAGGIO",
    distrattoriFacili: ["FORMA", "VEICOLO", "PROFESSIONE"],
    distrattoriDuri:   ["MOZZARELLA", "RICOTTA", "LATTICINIO"] },
  { id: "cat34", tipo: "categoriale",
    a: "AMERICA",  b: "CONTINENTE",   c: "ATLANTICO", risposta: "OCEANO",
    distrattoriFacili: ["EMOZIONE", "MOBILE", "FRUTTO"],
    distrattoriDuri:   ["GOLFO", "BAIA", "STRETTO"] },
  { id: "cat35", tipo: "categoriale",
    a: "BANANA",   b: "FRUTTO",       c: "BASILICO",  risposta: "ERBA",
    distrattoriFacili: ["PROFESSIONE", "VEICOLO", "MOBILE"],
    distrattoriDuri:   ["FOGLIA", "PIANTA", "ORTAGGIO"] },
  { id: "cat36", tipo: "categoriale",
    a: "PADELLA",  b: "UTENSILE",     c: "POLTRONA",  risposta: "MOBILE",
    distrattoriFacili: ["NUMERO", "EMOZIONE", "STAGIONE"],
    distrattoriDuri:   ["DIVANO", "POGGIATESTA", "SCHIENALE"] },
  { id: "cat37", tipo: "categoriale",
    a: "LUNA",     b: "SATELLITE",    c: "TERRA",     risposta: "PIANETA",
    distrattoriFacili: ["ANIMALE", "MOBILE", "FRUTTO"],
    distrattoriDuri:   ["COMETA", "ASTEROIDE", "METEORITE"] },
  { id: "cat38", tipo: "categoriale",
    a: "SOFÀ",     b: "MOBILE",       c: "LENZUOLO",  risposta: "TESSILE",
    distrattoriFacili: ["EMOZIONE", "BEVANDA", "FORMA"],
    distrattoriDuri:   ["FEDERA", "COPRILETTO", "BIANCHERIA"] },
  { id: "cat39", tipo: "categoriale",
    a: "CACTUS",   b: "PIANTA",       c: "TARANTOLA", risposta: "ARACNIDE",
    distrattoriFacili: ["EMOZIONE", "VEICOLO", "FORMA"],
    distrattoriDuri:   ["RAGNO", "SCORPIONE", "ARTROPODE"] },
  { id: "cat40", tipo: "categoriale",
    a: "OMBELICO", b: "PARTE DEL CORPO", c: "POLLICE", risposta: "DITO",
    distrattoriFacili: ["VEICOLO", "MOBILE", "FRUTTO"],
    distrattoriDuri:   ["FALANGE", "UNGHIA", "ARTO"] },
  { id: "cat41", tipo: "categoriale",
    a: "UVA",      b: "FRUTTO",       c: "GRANO",     risposta: "CEREALE",
    distrattoriFacili: ["EMOZIONE", "VEICOLO", "PROFESSIONE"],
    distrattoriDuri:   ["FARRO", "ORZO", "AVENA"] },
  { id: "cat42", tipo: "categoriale",
    a: "RANA",     b: "ANFIBIO",      c: "COCCODRILLO", risposta: "RETTILE",
    distrattoriFacili: ["MOBILE", "STAGIONE", "FRUTTO"],
    distrattoriDuri:   ["LUCERTOLA", "PALUDE", "SCAGLIA"] },
  { id: "cat43", tipo: "categoriale",
    a: "BISONTE",  b: "MAMMIFERO",    c: "PINGUINO",  risposta: "UCCELLO",
    distrattoriFacili: ["EMOZIONE", "FRUTTO", "FORMA"],
    distrattoriDuri:   ["PIUMA", "BECCO", "POLO"] },
  { id: "cat44", tipo: "categoriale",
    a: "SALICE",   b: "ALBERO",       c: "ORTENSIA",  risposta: "FIORE",
    distrattoriFacili: ["MOBILE", "VEICOLO", "PROFESSIONE"],
    distrattoriDuri:   ["PETALO", "BOCCIOLO", "VASO"] },
  { id: "cat45", tipo: "categoriale",
    a: "MIELE",    b: "DOLCIFICANTE", c: "SALE",      risposta: "CONDIMENTO",
    distrattoriFacili: ["ANIMALE", "EMOZIONE", "MOBILE"],
    distrattoriDuri:   ["PEPE", "SPEZIA", "AROMATIZZANTE"] },
  { id: "cat46", tipo: "categoriale",
    a: "ECLISSI",  b: "FENOMENO",     c: "TERREMOTO", risposta: "EVENTO",
    distrattoriFacili: ["MOBILE", "FRUTTO", "BEVANDA"],
    distrattoriDuri:   ["CATASTROFE", "CALAMITÀ", "DISASTRO"] },
  { id: "cat47", tipo: "categoriale",
    a: "ZINCO",    b: "METALLO",      c: "ARGILLA",   risposta: "MINERALE",
    distrattoriFacili: ["EMOZIONE", "BEVANDA", "PROFESSIONE"],
    distrattoriDuri:   ["TERRA", "CRETA", "ROCCIA"] },
  { id: "cat48", tipo: "categoriale",
    a: "ARIA",     b: "ELEMENTO",     c: "ROSSO",     risposta: "COLORE",
    distrattoriFacili: ["VEICOLO", "ANIMALE", "MOBILE"],
    distrattoriDuri:   ["TINTA", "TONALITÀ", "SFUMATURA"] },
  { id: "cat49", tipo: "categoriale",
    a: "DUOMO",    b: "EDIFICIO",     c: "PIAZZA",    risposta: "SPAZIO URBANO",
    distrattoriFacili: ["EMOZIONE", "FRUTTO", "VEICOLO"],
    distrattoriDuri:   ["VIA", "VIALE", "STRADA"] },
  { id: "cat50", tipo: "categoriale",
    a: "ETTARO",   b: "MISURA",       c: "EURO",      risposta: "MONETA",
    distrattoriFacili: ["EMOZIONE", "STAGIONE", "MOBILE"],
    distrattoriDuri:   ["DOLLARO", "VALUTA", "BANCONOTA"] },
] as const;

// ── ASTRATTE ────────────────────────────────────────────────────────────────
export const POOL_ASTRATTE: readonly AnalogiaItem[] = [
  { id: "ast01", tipo: "astratta",
    a: "LIBERTÀ",  b: "PRIGIONE",  c: "PACE",         risposta: "GUERRA",
    distrattoriFacili: ["PANE", "STELLA", "PALAZZO"],
    distrattoriDuri:   ["DISCUSSIONE", "ALLEANZA", "TREGUA"] },
  { id: "ast02", tipo: "astratta",
    a: "VERITÀ",   b: "MENZOGNA",  c: "GIUSTIZIA",    risposta: "INGIUSTIZIA",
    distrattoriFacili: ["BICICLETTA", "TÈ", "PINO"],
    distrattoriDuri:   ["LEGGE", "GIUDICE", "PROCESSO"] },
  { id: "ast03", tipo: "astratta",
    a: "AMORE",    b: "ODIO",      c: "FIDUCIA",      risposta: "SOSPETTO",
    distrattoriFacili: ["CAVALLO", "TAVOLO", "GIALLO"],
    distrattoriDuri:   ["AMICIZIA", "RISPETTO", "STIMA"] },
  { id: "ast04", tipo: "astratta",
    a: "RICORDO",  b: "OBLIO",     c: "SPERANZA",     risposta: "DISPERAZIONE",
    distrattoriFacili: ["MARTELLO", "PESCE", "RUOTA"],
    distrattoriDuri:   ["ATTESA", "RASSEGNAZIONE", "PAZIENZA"] },
  { id: "ast05", tipo: "astratta",
    a: "CORAGGIO", b: "PAURA",     c: "VIRTÙ",        risposta: "VIZIO",
    distrattoriFacili: ["PIATTO", "LAGO", "PORTA"],
    distrattoriDuri:   ["PECCATO", "TENTAZIONE", "DEBOLEZZA"] },
  { id: "ast06", tipo: "astratta",
    a: "INIZIO",   b: "FINE",      c: "NASCITA",      risposta: "MORTE",
    distrattoriFacili: ["CHITARRA", "PIZZA", "MAGLIA"],
    distrattoriDuri:   ["VECCHIAIA", "MALATTIA", "ETERNITÀ"] },
  { id: "ast07", tipo: "astratta",
    a: "PUBBLICO", b: "PRIVATO",   c: "PALESE",       risposta: "SEGRETO",
    distrattoriFacili: ["PERA", "TRENO", "STELLA"],
    distrattoriDuri:   ["NASCOSTO", "MISTERO", "OCCULTO"] },
  { id: "ast08", tipo: "astratta",
    a: "RICCHEZZA", b: "MISERIA",  c: "ABBONDANZA",   risposta: "CARESTIA",
    distrattoriFacili: ["OROLOGIO", "VIOLINO", "CAVALLO"],
    distrattoriDuri:   ["RACCOLTO", "SEMINA", "SICCITÀ"] },
  { id: "ast09", tipo: "astratta",
    a: "ORDINE",   b: "CAOS",      c: "ARMONIA",      risposta: "DISCORDIA",
    distrattoriFacili: ["LAMPADA", "BICCHIERE", "BANDIERA"],
    distrattoriDuri:   ["DISACCORDO", "LITE", "CONFUSIONE"] },
  { id: "ast10", tipo: "astratta",
    a: "FORZA",    b: "FRAGILITÀ", c: "POTERE",       risposta: "DEBOLEZZA",
    distrattoriFacili: ["GUFO", "ZAINO", "FORCHETTA"],
    distrattoriDuri:   ["AUTORITÀ", "INFLUENZA", "COMANDO"] },
  { id: "ast11", tipo: "astratta",
    a: "GENEROSITÀ", b: "AVARIZIA", c: "UMILTÀ",      risposta: "ORGOGLIO",
    distrattoriFacili: ["PIANO", "FIUME", "MATITA"],
    distrattoriDuri:   ["SUPERBIA", "VANITÀ", "ARROGANZA"] },
  { id: "ast12", tipo: "astratta",
    a: "PRESENTE",  b: "PASSATO",  c: "REALTÀ",       risposta: "SOGNO",
    distrattoriFacili: ["PIETRA", "ZUCCHERO", "OMBRELLO"],
    distrattoriDuri:   ["FANTASIA", "ILLUSIONE", "IMMAGINAZIONE"] },
  { id: "ast13", tipo: "astratta",
    a: "SAGGEZZA",  b: "STOLTEZZA", c: "PRUDENZA",    risposta: "AVVENTATEZZA",
    distrattoriFacili: ["TENDA", "BARCA", "TROMBA"],
    distrattoriDuri:   ["IMPULSIVITÀ", "TEMERARIETÀ", "INCOSCIENZA"] },
  { id: "ast14", tipo: "astratta",
    a: "GIOIA",    b: "DOLORE",    c: "ALLEGRIA",     risposta: "TRISTEZZA",
    distrattoriFacili: ["VASO", "TROMBA", "BANCHINA"],
    distrattoriDuri:   ["MALINCONIA", "AFFLIZIONE", "SCONFORTO"] },
  { id: "ast15", tipo: "astratta",
    a: "PROGRESSO", b: "REGRESSO", c: "AVANZAMENTO",  risposta: "ARRETRAMENTO",
    distrattoriFacili: ["TAPPETO", "CAMINO", "BARCA"],
    distrattoriDuri:   ["DECADENZA", "DECLINO", "STAGNAZIONE"] },
  { id: "ast16", tipo: "astratta",
    a: "INNOCENZA", b: "COLPA",    c: "PUREZZA",      risposta: "CORRUZIONE",
    distrattoriFacili: ["CHIAVE", "RUOTA", "NUVOLA"],
    distrattoriDuri:   ["PECCATO", "MACCHIA", "VIZIO"] },
  { id: "ast17", tipo: "astratta",
    a: "FEDELTÀ",   b: "TRADIMENTO", c: "LEALTÀ",     risposta: "INGANNO",
    distrattoriFacili: ["LAGO", "SPIGA", "FINESTRA"],
    distrattoriDuri:   ["FALSITÀ", "DOPPIEZZA", "FRODE"] },
  { id: "ast18", tipo: "astratta",
    a: "GIORNO",    b: "TEMPO",    c: "CHILOMETRO",   risposta: "DISTANZA",
    distrattoriFacili: ["EMOZIONE", "FRUTTO", "ANIMALE"],
    distrattoriDuri:   ["SPAZIO", "PERCORSO", "LUNGHEZZA"] },
  { id: "ast19", tipo: "astratta",
    a: "SUCCESSO",  b: "FALLIMENTO", c: "GLORIA",     risposta: "OBLIO",
    distrattoriFacili: ["PALA", "CAMICIA", "CAVALLO"],
    distrattoriDuri:   ["VERGOGNA", "DIMENTICANZA", "ROVINA"] },
  { id: "ast20", tipo: "astratta",
    a: "ESISTENZA", b: "VITA",     c: "ESPERIENZA",   risposta: "VISSUTO",
    distrattoriFacili: ["MOTORE", "FAGIOLO", "TAMBURO"],
    distrattoriDuri:   ["MEMORIA", "RICORDO", "STORIA"] },
  { id: "ast21", tipo: "astratta",
    a: "CERTEZZA",  b: "DUBBIO",   c: "CONVINZIONE",  risposta: "ESITAZIONE",
    distrattoriFacili: ["MARTELLO", "STIVALE", "VIOLA"],
    distrattoriDuri:   ["PERPLESSITÀ", "INDECISIONE", "TITUBANZA"] },
  { id: "ast22", tipo: "astratta",
    a: "BELLEZZA",  b: "BRUTTEZZA", c: "GRAZIA",      risposta: "SGRAZIA",
    distrattoriFacili: ["TAVOLO", "ZAFFERANO", "MURO"],
    distrattoriDuri:   ["GOFFAGGINE", "ROZZEZZA", "VOLGARITÀ"] },
  { id: "ast23", tipo: "astratta",
    a: "GENIO",     b: "STUPIDITÀ", c: "INGEGNO",     risposta: "OTTUSITÀ",
    distrattoriFacili: ["VASO", "PESCA", "CHIODO"],
    distrattoriDuri:   ["OTTUSAGGINE", "TARDEZZA", "OBTUSITÀ"] },
  { id: "ast24", tipo: "astratta",
    a: "PIETÀ",     b: "CRUDELTÀ", c: "COMPASSIONE",  risposta: "FEROCIA",
    distrattoriFacili: ["MARGHERITA", "RICOTTA", "SCALA"],
    distrattoriDuri:   ["SPIETATEZZA", "DUREZZA", "BARBARIE"] },
  { id: "ast25", tipo: "astratta",
    a: "MODESTIA",  b: "VANITÀ",   c: "RISERBO",      risposta: "OSTENTAZIONE",
    distrattoriFacili: ["LAMPADA", "OLIVA", "CASCATA"],
    distrattoriDuri:   ["SFARZO", "ESIBIZIONISMO", "POMPOSITÀ"] },
  { id: "ast26", tipo: "astratta",
    a: "AUDACIA",   b: "TIMIDEZZA", c: "INTRAPRENDENZA", risposta: "PIGRIZIA",
    distrattoriFacili: ["RADIO", "FRUTTA", "MURO"],
    distrattoriDuri:   ["INERZIA", "INDOLENZA", "FIACCHEZZA"] },
  { id: "ast27", tipo: "astratta",
    a: "SINCERITÀ", b: "IPOCRISIA", c: "ONESTÀ",       risposta: "DISONESTÀ",
    distrattoriFacili: ["TAVOLO", "PORTA", "POMA"],
    distrattoriDuri:   ["FALSITÀ", "FRODE", "SLEALTÀ"] },
  { id: "ast28", tipo: "astratta",
    a: "CALMA",     b: "PANICO",    c: "SERENITÀ",     risposta: "ANSIA",
    distrattoriFacili: ["FORNO", "CHIODO", "ZAINO"],
    distrattoriDuri:   ["INQUIETUDINE", "AGITAZIONE", "TENSIONE"] },
  { id: "ast29", tipo: "astratta",
    a: "SPLENDORE", b: "SQUALLORE", c: "MAGNIFICENZA", risposta: "SOBRIETÀ",
    distrattoriFacili: ["UCCELLO", "BICCHIERE", "GUFO"],
    distrattoriDuri:   ["AUSTERITÀ", "MISURA", "SEMPLICITÀ"] },
  { id: "ast30", tipo: "astratta",
    a: "EQUITÀ",    b: "PARZIALITÀ", c: "IMPARZIALITÀ", risposta: "FAVORITISMO",
    distrattoriFacili: ["CAMINO", "TROMBA", "CASSETTO"],
    distrattoriDuri:   ["DISCRIMINAZIONE", "PREFERENZA", "CLIENTELISMO"] },
  { id: "ast31", tipo: "astratta",
    a: "NOSTALGIA", b: "INDIFFERENZA", c: "RIMPIANTO", risposta: "DISTACCO",
    distrattoriFacili: ["MOTORE", "TENDA", "GIARDINO"],
    distrattoriDuri:   ["FREDDEZZA", "DISINTERESSE", "APATIA"] },
  { id: "ast32", tipo: "astratta",
    a: "EUFORIA",   b: "DEPRESSIONE", c: "ESALTAZIONE", risposta: "AVVILIMENTO",
    distrattoriFacili: ["CAVALLO", "MURO", "RADICE"],
    distrattoriDuri:   ["MALINCONIA", "SCONFORTO", "ABBATTIMENTO"] },
  { id: "ast33", tipo: "astratta",
    a: "SAPIENZA",  b: "IGNORANZA", c: "CULTURA",      risposta: "ANALFABETISMO",
    distrattoriFacili: ["PORTA", "MARTELLO", "ZUCCA"],
    distrattoriDuri:   ["INCOMPETENZA", "ROZZEZZA", "INESPERIENZA"] },
  { id: "ast34", tipo: "astratta",
    a: "ONORE",     b: "DISONORE",  c: "PRESTIGIO",    risposta: "DISCREDITO",
    distrattoriFacili: ["RADIO", "VASO", "PASTA"],
    distrattoriDuri:   ["VERGOGNA", "INFAMIA", "OBBROBRIO"] },
  { id: "ast35", tipo: "astratta",
    a: "PIENEZZA",  b: "MANCANZA",  c: "COMPLETEZZA",  risposta: "CARENZA",
    distrattoriFacili: ["RUBINETTO", "POLLO", "TROMBA"],
    distrattoriDuri:   ["LACUNA", "VUOTO", "ASSENZA"] },
  { id: "ast36", tipo: "astratta",
    a: "INDULGENZA", b: "SEVERITÀ", c: "TOLLERANZA",   risposta: "INTRANSIGENZA",
    distrattoriFacili: ["LIBRO", "BARCA", "FORMA"],
    distrattoriDuri:   ["DUREZZA", "RIGIDITÀ", "INFLESSIBILITÀ"] },
  { id: "ast37", tipo: "astratta",
    a: "SOLIDARIETÀ", b: "EGOISMO", c: "ALTRUISMO",    risposta: "INDIVIDUALISMO",
    distrattoriFacili: ["CIPOLLA", "FORCHETTA", "TENDA"],
    distrattoriDuri:   ["NARCISISMO", "ARRIVISMO", "MENEFREGHISMO"] },
  { id: "ast38", tipo: "astratta",
    a: "RAGIONE",   b: "SENTIMENTO", c: "LOGICA",      risposta: "EMOZIONE",
    distrattoriFacili: ["MOBILE", "RADICE", "POSTA"],
    distrattoriDuri:   ["PASSIONE", "ISTINTO", "IMPULSO"] },
  { id: "ast39", tipo: "astratta",
    a: "AZIONE",    b: "INERZIA",   c: "MOVIMENTO",    risposta: "IMMOBILITÀ",
    distrattoriFacili: ["LIMONE", "VIOLA", "CAMINO"],
    distrattoriDuri:   ["STATICITÀ", "QUIETE", "FERMEZZA"] },
  { id: "ast40", tipo: "astratta",
    a: "REGOLA",    b: "ECCEZIONE", c: "NORMA",        risposta: "DEROGA",
    distrattoriFacili: ["GUFO", "RADIO", "MELANZANA"],
    distrattoriDuri:   ["TRASGRESSIONE", "INFRAZIONE", "VIOLAZIONE"] },
  { id: "ast41", tipo: "astratta",
    a: "PERMESSO",  b: "DIVIETO",   c: "AUTORIZZAZIONE", risposta: "PROIBIZIONE",
    distrattoriFacili: ["CAVALLO", "PIATTO", "STELLA"],
    distrattoriDuri:   ["INTERDIZIONE", "INIBIZIONE", "BANDO"] },
  { id: "ast42", tipo: "astratta",
    a: "COSTANZA",  b: "INCOSTANZA", c: "CONTINUITÀ",  risposta: "DISCONTINUITÀ",
    distrattoriFacili: ["MURO", "POLLO", "VIOLINO"],
    distrattoriDuri:   ["INTERMITTENZA", "INSTABILITÀ", "PRECARIETÀ"] },
  { id: "ast43", tipo: "astratta",
    a: "CHIAREZZA", b: "CONFUSIONE", c: "LIMPIDEZZA",  risposta: "AMBIGUITÀ",
    distrattoriFacili: ["BARCA", "TENDA", "FRUTTA"],
    distrattoriDuri:   ["VAGHEZZA", "OPACITÀ", "EQUIVOCO"] },
  { id: "ast44", tipo: "astratta",
    a: "ASSENSO",   b: "OPPOSIZIONE", c: "ACCETTAZIONE", risposta: "RIFIUTO",
    distrattoriFacili: ["CAMPANA", "FIORE", "POLLO"],
    distrattoriDuri:   ["DINIEGO", "RESPINGIMENTO", "RIPULSA"] },
  { id: "ast45", tipo: "astratta",
    a: "ENTUSIASMO", b: "APATIA",   c: "ARDORE",       risposta: "INDIFFERENZA",
    distrattoriFacili: ["CARTA", "CAVALLO", "MOLA"],
    distrattoriDuri:   ["TIEPIDEZZA", "INERZIA", "DISINTERESSE"] },
  { id: "ast46", tipo: "astratta",
    a: "RISPETTO",  b: "DISPREZZO", c: "REVERENZA",    risposta: "SCHERNO",
    distrattoriFacili: ["BOTTE", "FUNGO", "ZAINO"],
    distrattoriDuri:   ["DERISIONE", "BEFFA", "DILEGGIO"] },
  { id: "ast47", tipo: "astratta",
    a: "AMICIZIA",  b: "INIMICIZIA", c: "SODALIZIO",   risposta: "OSTILITÀ",
    distrattoriFacili: ["MARTELLO", "PIANO", "POSTA"],
    distrattoriDuri:   ["AVVERSIONE", "ANTIPATIA", "RUGGINE"] },
  { id: "ast48", tipo: "astratta",
    a: "DESIDERIO", b: "AVVERSIONE", c: "BRAMOSIA",    risposta: "REPULSIONE",
    distrattoriFacili: ["RUOTA", "GHIANDA", "VASO"],
    distrattoriDuri:   ["RIBREZZO", "RIPUGNANZA", "DISGUSTO"] },
  { id: "ast49", tipo: "astratta",
    a: "PRESENZA",  b: "ASSENZA",   c: "PARTECIPAZIONE", risposta: "DISERZIONE",
    distrattoriFacili: ["RUOTA", "MUSCO", "PORTA"],
    distrattoriDuri:   ["DISTACCO", "RINUNCIA", "RITIRO"] },
  { id: "ast50", tipo: "astratta",
    a: "VITALITÀ",  b: "STANCHEZZA", c: "VIGORE",      risposta: "SPOSSATEZZA",
    distrattoriFacili: ["RUBINETTO", "TENDA", "FIORDALISO"],
    distrattoriDuri:   ["LANGUORE", "FIACCHEZZA", "PROSTRAZIONE"] },
] as const;

export function getPoolByTipo(tipo: TipoAnalogia): readonly AnalogiaItem[] {
  switch (tipo) {
    case "oppositiva":  return POOL_OPPOSITIVE;
    case "funzionale":  return POOL_FUNZIONALI;
    case "categoriale": return POOL_CATEGORIALI;
    case "astratta":    return POOL_ASTRATTE;
  }
}
